# Basic
name:               "Wesley K Chang"
title:              "Wesley K Chang Research Page"
description:        "this is a page for Wesley Chang's personal research page"
google analytics:   UA-174999397-1

# URL
url:                http://wesleykchang.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "resume"
    href:           "/resume"
  - name:           "publications"
    href:           "/publication"
  - name:           "research"
    href:           "/research"
    
# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
